update zaks personal project ideact.it to README
NicoleJaneway/ea-software-engineers pull request #4
Opened 2023-04-11 21:48 UTC by zakwatts

Add Ideact.it to the personal project section.

2023-04-11 22:04 UTC, zakwatts commented
small change made to personal project name and description below mine to make it clearer where to add a project

2023-04-11 22:15 UTC, zakwatts commented
<img width="431" alt="Screenshot 2023-04-11 at 23 13 20" src="https://user-images.githubusercontent.com/47150349/231300666-7104aadd-946f-4b3a-b78e-3e89d7b849e3.png">

I found doing "gem CONTRIBUTING.md" create a load of files. Is that normal?

2023-04-11 22:16 UTC, zakwatts commented
I would add this as a task for you but I don't think you sent me a request to help manage the repo. But you should update how frequent office hours are on it and also add a link to where you think is the best place to direct people for that.

2023-04-13 19:39 UTC, NicoleJaneway requested changes

2023-04-13 19:39 UTC, NicoleJaneway commented on CONTRIBUTING.md
> +If you get stuck or you are unsure about something pop into the EA Software Engineers office hours for help.
Can you capitalize Office Hours, add this link (https://docs.google.com/presentation/d/1T11dj1I3c23ZMLGWL-EYZVVJkgOv9coNR1355MWojOA/edit#slide=id.g219723c9878_0_39), and add that Office Hours are the second Monday of every month?

2023-04-13 19:39 UTC, NicoleJaneway commented on CONTRIBUTING.md
> +To contribute make sure to fork this repository, push your changes to that forked repository, then submit a pull request to this repository for your work to be merged.
Good idea 🙂

2023-04-13 19:39 UTC, NicoleJaneway commented on CONTRIBUTING.md
> +   [Check out this awesome blog post by Chris Beams for more information.][chris-beams]
Whitespace error?

2023-04-13 19:39 UTC, NicoleJaneway commented on README.md
> +# EA Software Engineers Awesome List [Awesome][awesome-link]
Can we put this back?

2023-04-13 19:39 UTC, NicoleJaneway commented on README.md
> +- [Ideact.it ](https://app.ideact.it/)– A tool to evaluate different cause areas and ideas by assigning significance values to different variables. The tool tries to combine the ITN framework with pe
Yay!

2023-04-13 19:39 UTC, NicoleJaneway commented on README.md
> +- [Your Project Name]() – A short description about your project
Good idea!!

2023-04-13 19:39 UTC, NicoleJaneway commented on README.md
> +This project was initially created with [Cookiecutter][cookiecutter] and the custom [cookiecutter-awesome][cookiecutter-awesome] 🍪
please revert

2023-04-13 19:39 UTC, NicoleJaneway commented on README.md
> +[CC0][cc0-link]
please revert

2023-04-21 20:35 UTC, NicoleJaneway approved these changes

2023-04-21 20:35 UTC, merged